# Generated by Django 5.2 on 2025-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_classifier_code'),
        ('users', '0006_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('classifier__isnull', False), ('organization__isnull', False)), fields=('classifier', 'organization'), name='unique_classifier_organization_of_user_if_set'),
        ),
    ]
