# Generated by Django 5.2 on 2025-08-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options_alter_user_classifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_file_upload_only_from_camera",
            field=models.BooleanField(
                default=False, verbose_name="enable file upload only from camera"
            ),
        ),
    ]
