# Generated by Django 5.2 on 2025-10-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_alter_classifier_options_alter_organization_options_and_more'),
        ('users', '0009_user_enable_file_upload_only_from_camera'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='organization_required_only_for_workers',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='classifier_required_only_for_workers',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_classifier_organization_of_user_if_set',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('classifier__isnull', True), ('organization__isnull', True)), models.Q(('classifier__isnull', False), ('organization__isnull', False)), _connector='OR'), name='classifier_and_organization_use_together', violation_error_message='Classifier and Organization must be used|not used together'),
        ),
    ]
