# Generated by Django 5.2 on 2025-10-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_alter_classifier_options_alter_organization_options_and_more'),
        ('users', '0010_remove_user_organization_required_only_for_workers_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='user',
            name='classifier_and_organization_use_together',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('classifier__isnull', True), ('organization__isnull', True)), models.Q(('classifier__isnull', False), ('organization__isnull', False)), _connector='OR'), name='classifier_and_organization_use_together', violation_error_message='Classifier and Organization must be used | not used together'),
        ),
    ]
