# Generated by Django 5.2 on 2025-04-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='code',
            field=models.CharField(default=0, max_length=18, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
