# Generated by Django 5.2 on 2025-04-29 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_activitystatistics_supervision'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervision',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
