# Generated by Django 5.2 on 2025-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_supervision_end_date_supervision_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
