# Generated by Django 5.2 on 2025-04-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_alter_commentimage_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentimage",
            old_name="url",
            new_name="image",
        ),
    ]
