# Generated by Django 5.2 on 2025-05-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_rename_url_commentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
