# Generated by Django 5.2 on 2025-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_supervision_failed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervision',
            name='failed',
        ),
        migrations.AddField(
            model_name='supervision',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
