# Generated by Django 5.2 on 2025-07-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0012_failure_activitystatistics_failure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="failure",
            options={"verbose_name": "Failure", "verbose_name_plural": "Failures"},
        ),
        migrations.RemoveField(
            model_name="supervision",
            name="name",
        ),
        migrations.AddField(
            model_name="activitystatistics",
            name="verification_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="verification_date"
            ),
        ),
        migrations.AddField(
            model_name="activitystatistics",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
        migrations.AddField(
            model_name="supervision",
            name="verification_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="verification_date"
            ),
        ),
        migrations.AddField(
            model_name="supervision",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
    ]
