# Generated by Django 5.2 on 2025-08-03 13:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_alter_failure_options_remove_supervision_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
