# Generated by Django 5.2 on 2025-09-30 18:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_comment_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='coordinates'),
        ),
    ]
