# Generated by Django 5.2 on 2025-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_alter_comment_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='planned_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='planned end time'),
        ),
        migrations.AddField(
            model_name='supervision',
            name='planned_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='planned start time'),
        ),
    ]
