# Generated by Django 5.2.9 on 2025-12-10 16:46

from django.db import migrations
from django.contrib.gis.db.models.fields import PointField


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_delete_commentimage'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "analytics_comment" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "created_date" timestamp with time zone NOT NULL,
                "updated_date" timestamp with time zone NOT NULL,
                "text" text NOT NULL,
                "created_by_id" bigint NULL,
                "updated_by_id" bigint NULL,
                "activity_statistics_id" bigint NOT NULL,
                "coordinates" geometry(POINT,4326) NULL
            );
            
            -- Add foreign key constraints if they don't exist
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'analytics_comment_created_by_id_392fc3dd_fk_users_user_id'
                ) THEN
                    ALTER TABLE "analytics_comment" 
                    ADD CONSTRAINT "analytics_comment_created_by_id_392fc3dd_fk_users_user_id" 
                    FOREIGN KEY ("created_by_id") REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED;
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'analytics_comment_updated_by_id_70a65685_fk_users_user_id'
                ) THEN
                    ALTER TABLE "analytics_comment" 
                    ADD CONSTRAINT "analytics_comment_updated_by_id_70a65685_fk_users_user_id" 
                    FOREIGN KEY ("updated_by_id") REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED;
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'analytics_comment_activity_statistics__a34742b8_fk_analytics'
                ) THEN
                    ALTER TABLE "analytics_comment" 
                    ADD CONSTRAINT "analytics_comment_activity_statistics__a34742b8_fk_analytics" 
                    FOREIGN KEY ("activity_statistics_id") REFERENCES "analytics_activitystatistics"("id") DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
            
            -- Create index for coordinates if it doesn't exist
            CREATE INDEX IF NOT EXISTS "analytics_comment_coordinates_09f2f162_id" 
            ON "analytics_comment" USING GIST ("coordinates");
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
