# Generated by Django 5.2 on 2025-04-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "layouts",
            "0003_alter_activity_options_alter_activitygroup_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="activitygroup",
            options={"ordering": ("order",)},
        ),
        migrations.AlterOrderWithRespectTo(
            name="activity",
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name="activitygroup",
            order_with_respect_to=None,
        ),
    ]
