# Generated by Django 5.2 on 2025-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_failure_btn', models.BooleanField(default=False, help_text='Hide failure button display', verbose_name='hide failure button')),
                ('hide_info_btn', models.BooleanField(default=False, help_text='Hide info button display', verbose_name='hide info button')),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
