#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python manage.py migrate
python /app/create_superuser.py

exec gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app

